NASDAQ_100 = [
    "AAPL","MSFT","AMZN","NVDA","GOOG","GOOGL","META","TSLA","PEP","COST",
    "AVGO","NFLX","ADBE","CSCO","AMD","TXN","INTC","HON","AMAT","INTU",
    "QCOM","AMGN","BKNG","MU","LRCX","MDLZ","PANW","ADP","SBUX","VRTX",
    "REGN","GILD","PYPL","ADI","CSX","MRNA","MAR","KLAC","CHTR","PDD",
    "ABNB","NXPI","KDP","CDNS","FTNT","MELI","WDAY","SNPS","CRWD","ORLY",
    "CTAS","PCAR","ODFL","MNST","EXC","LULU","AEP","PAYX","EA","TEAM",
    "DLTR","AZN","IDXX","XEL","CTSH","FAST","ROST","ADSK","BIIB","WBD",
    "PANW","TTWO","CPRT","CEG","VRSK","KHC","ALGN","GFS","ZS","ON",
    "MDB","MRVL","BKR","VRSN","DDOG","SPLK","SWKS","INTU","OKTA","ANSS",
    "FISV","TTD","VERX","PAYC","LCID","RIVN","SIRI","FOX","FOXA"
]
